[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = ['Dein']
if = '!exists("g:vscode")'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = ['DeinUpdate']
if = '!exists("g:vscode")'

##########################################################

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
if = '!exists("g:vscode")'
depends = ['kyazdani42/nvim-web-devicons']
hook_source = '''
    lua require('galaxyline/eviline')
'''

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
if = '!exists("g:vscode")'
depends = ['kyazdani42/nvim-web-devicons']
hook_add = '''
  let g:nvim_tree_auto_close = 1
  let g:nvim_tree_quit_on_open = 1
  let g:nvim_tree_indent_markers = 1
  let g:nvim_tree_width_allow_resize  = 1
  let g:nvim_tree_show_icons = {
    \ 'git': 1,
    \ 'folders': 1,
    \ 'files': 1,
    \ }
'''
hook_source = '''
  nnoremap tt :NvimTreeOpen<CR>
  nnoremap q :NvimTreeClose<CR>
'''

[[plugins]]
repo = 'Yggdroot/LeaderF'
if = '!exists("g:vscode")'
hook_post_update = '''
  ./install.sh
'''
on_map = ['<leader>ff']
hook_add = '''
let g:Lf_ShortcutF = "<leader>ff"
let g:Lf_CommandMap = {'<C-K>': ['<C-e>'], '<C-J>': ['<C-n>']}

let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
'''
hook_source = '''
noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
noremap <leader>fr :<C-U><C-R>=printf("Leaderf rg %s", "")<CR><CR>
'''
