# [[plugins]]
# repo = 'rhysd/accelerated-jk'
# on_map = '<Plug>'
# hook_add = '''
#   nmap <silent>n <Plug>(accelerated_jk_gj)
#   nmap <silent>e <Plug>(accelerated_jk_gk)
# '''

# [[plugins]]
# repo = 'luochen1990/rainbow'
# on_ft = ["html", "css", "javascript", "javascriptreact","go","rust","vim","less","sass","json","toml"]
# hook_source = '''
# 	let g:rainbow_active = 1
# '''

# [[plugins]]
# repo = 'itchyny/vim-cursorword'
# on_event = ["BufReadPre","BufNewFile"]
# hook_source = '''
#    augroup user_plugin_cursorword
#       autocmd!
#       autocmd FileType defx,denite,fern,clap,vista let b:cursorword = 0
#       autocmd WinEnter * if &diff || &pvw | let b:cursorword = 0 | endif
#       autocmd InsertEnter * let b:cursorword = 0
#       autocmd InsertLeave * let b:cursorword = 1
#     augroup END
# '''

[[plugins]]
repo = 'tpope/vim-surround'
on_event = ["BufReadPre","BufNewFile"]

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = ["BufReadPre","BufNewFile"]

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = ['FloatermNew', 'FloatermToggle', 'FloatermPrev', 'FloatermNext', 'FloatermSend']
hook_source= '''
    let g:floaterm_position = 'center'
    let g:floaterm_wintype = 'floating'
    " Set floaterm window's background to black
    hi Floaterm guibg=black
    " Set floating window border line color to cyan, and background to orange
    hi FloatermBorder guibg=none guifg=cyan
'''

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'MundoToggle'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = '<Plug>(EasyAlign)'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = "junegunn/fzf"
hook_post_update = '''
    call fzf#install()
'''

[[plugins]]
repo = "junegunn/fzf.vim"
on_cmd = ['Files', 'Buffers']
hook_add = '''
    let g:fzf_preview_window = 'right:60%'
    nnoremap <silent> <Leader>ff :Files<CR>
    nnoremap <silent> <Leader>fb :Buffers<CR>
    nnoremap <silent> <Leader>frg :Rg<CR>
    nnoremap <silent> <Leader>fag :Ag<CR>
'''

