[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
if = '!exists("g:vscode")'


[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = [ 'Dockerfile', 'docker-compose' ]
if = '!exists("g:vscode")'

[[plugins]]
repo = 'vimwiki/vimwiki'
on_ft = ['markdown', 'wiki']
if = '!exists("g:vscode")'
