[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = [ 'Dockerfile', 'docker-compose' ]

[[plugins]]
repo = 'vimwiki/vimwiki'
on_ft = ['markdown', 'wiki']
