# [[plugins]]
# repo = 'Yggdroot/indentLine'
# on_event = 'BufReadPre'
# on_cmd = ['IndentLinesToggle']
# hook_source = '''
#     let g:indentLine_fileTypeExclude = ['defx','dbui','vista_kind','vista','dashboard', 'help']
#     let g:indentLine_concealcursor = 'niv'
#     " let g:indentLine_showFirstIndentLevel =1
# '''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['go', 'java', 'javascript', 'typescript', 'lua', 'scala' ]
on_cmd = 'QuickRun'
hook_add = '''
    nmap <Leader>r <Plug>(quickrun)
'''
hook_source = '''
    let g:quickrun_config = {
    \   "_" : {
    \       "outputter" : "message",
    \   },
    \}
    let g:quickrun_no_default_key_mappings = 1
'''

[[plugins]]
repo = 'vim-test/vim-test'
on_ft = ['go', 'java', 'javascript', 'typescript', 'lua', 'scala' ]
hook_add = '''
    " these "Ctrl mappings" work well when Caps Lock is mapped to Ctrl
    nmap <silent> t<C-n> :TestNearest<CR>
    nmap <silent> t<C-f> :TestFile<CR>
    nmap <silent> t<C-s> :TestSuite<CR>
    nmap <silent> t<C-l> :TestLast<CR>
    nmap <silent> t<C-g> :TestVisit<CR>
'''
hook_source = '''
  let test#strategy = "neovim"
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'sbdchd/neoformat'
on_cmd = ['Neoformat', 'Neoformat!']

[[plugins]]
repo = 'honza/vim-snippets'
depends = 'coc.nvim'
if = 'has("python3")'
merged = 0

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"
merged = 0
hook_add = '''
    let g:coc_snippet_next = '<TAB>'
    let g:coc_snippet_prev = '<S-TAB>'
    let g:snips_author = 'lj.liujun'
    let g:coc_status_error_sign = '•'
    let g:coc_status_warning_sign = '•'
    let g:coc_global_extensions =[
		\ 'coc-marketplace',
		\ 'coc-snippets',
		\ 'coc-pairs',
		\ 'coc-json',
		\ 'coc-highlight',
		\ 'coc-emoji',
		\ 'coc-lists',
		\ 'coc-stylelint',
		\ 'coc-yaml',
		\ 'coc-yank',
		\ 'coc-actions',
		\ 'coc-vimlsp',
		\ 'coc-vetur',
		\ 'coc-emmet',
		\ 'coc-prettier',
		\ 'coc-diagnostic',
		\ 'coc-translator',
    \ 'coc-metals',
        \]

    " \ 'coc-tabnine',
    " \ 'coc-lua',
    augroup coc_event
      autocmd!
      " Highlight the symbol and its references when holding the cursor.
      autocmd CursorHold * silent call CocActionAsync('highlight')
      autocmd ColorScheme * highlight! CocHighlightText guibg=#054c20 ctermbg=023

      autocmd BufWritePre *.go silent :call CocAction('runCommand', 'editor.action.organizeImport')
    augroup end

    "Use tab for trigger completion with characters ahead and navigate
    inoremap <silent><expr> <TAB>
          \ <SID>check_right_bracket() ? "\<Right>" :
          \ pumvisible() ? "\<C-n>" :
          \ v:lua.check_back_space() ? "\<TAB>" :
          \ coc#refresh()
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
    inoremap <expr><C-e> pumvisible() ? "\<C-p>" : "\<C-e>"
    function s:check_right_bracket() abort
      let c = getline('.')[col('.')-1]
      return c =~ '[\)\]\}]' || c == '"' || c == "'" || c == ';'
    endf

    inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

    " Use `[g` and `]g` to navigate diagnostics
    nmap <silent> [g <Plug>(coc-diagnostic-prev)
    nmap <silent> ]g <Plug>(coc-diagnostic-next)

    " GoTo code navigation.
    nmap <silent> gd <Plug>(coc-definition)
    nmap <silent> gy <Plug>(coc-type-definition)
    nmap <silent> gi <Plug>(coc-implementation)
    nmap <silent> gr <Plug>(coc-references)

    " Symbol renaming.
    nmap <leader>rn <Plug>(coc-rename)

    " Use K to show documentation in preview window.
    nnoremap <silent><leader>k :call <SID>show_documentation()<CR>
    function! s:show_documentation()
     if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
     else
      call CocAction('doHover')
     endif
   endfunction

    " Show all diagnostics.
    nnoremap <silent> <leader>dg  :<C-u>CocList diagnostics<cr>
    " Manage extensions.
    nnoremap <silent> <leader>ex  :<C-u>CocList extensions<cr>
    " Show commands.
    nnoremap <silent> <leader>cm  :<C-u>CocList commands<cr>
    " Find symbol of current document.
    nnoremap <silent> <leader>ol  :<C-u>CocList outline<cr>
    " Search workspace symbols.
    nnoremap <silent> <leader>sb  :<C-u>CocList -I symbols<cr>

    " Remap for do codeAction of selected region
    function! s:cocActionsOpenFromSelected(type) abort
        execute 'CocCommand actions.open ' . a:type
    endfunction
    xmap <silent> <leader>ca :<C-u>execute 'CocCommand actions.open ' . visualmode()<CR>
    nmap <silent> <leader>ca :<C-u>set operatorfunc=<SID>cocActionsOpenFromSelected<CR>g@

    " Map function and class text objects
    " NOTE: Requires 'textDocument.documentSymbol' support from the language server.
    xmap uf <Plug>(coc-funcobj-i)
    omap uf <Plug>(coc-funcobj-i)
    xmap af <Plug>(coc-funcobj-a)
    omap af <Plug>(coc-funcobj-a) 

    " coc-translator
    nmap <leader>ts <Plug>(coc-translator-p)
    " coc-yank
    nnoremap <silent> <leader>ya :<C-u>CocList -A --normal yank<cr>
'''
