[[plugins]]
merged = 1
repo = 'sheerun/vim-polyglot'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
if = '!exists("g:vscode")'
hook_source = '''
  lua require'colorizer'.setup()
'''


# set background=dark
# " colorscheme gruvbox8
# colorscheme gruvbox
# " colorscheme onedark
# " colorscheme sonokai
[[plugins]]
repo = 'sainnhe/sonokai'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'morhetz/gruvbox'
if = '!exists("g:vscode")'
hook_source = '''
  lua vim.cmd('set background=dark')
  lua vim.cmd('colorscheme gruvbox')
'''

[[plugins]]
repo = 'joshdick/onedark.vim'
if = '!exists("g:vscode")'


