[[plugins]]
merged = 1
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_source = '''
  lua require'colorizer'.setup()
'''

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'joshdick/onedark.vim'


