# [[plugins]]
# repo = 'mhinz/vim-signify'
# on_event = ['BufReadPre','BufNewFile']
# hook_source = '''
#     let g:signify_sign_add = '▋'
#     let g:signify_sign_change = '▋'
#     let g:signify_sign_delete = '▋'
#     let g:signify_sign_delete_first_line = '▘'
#     let g:signify_sign_show_count = 0
# '''
