[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['go', 'java', 'javascript', 'typescript', 'lua', 'scala' ]
on_cmd = 'QuickRun'
if = '!exists("g:vscode")'
hook_add = '''
let g:quickrun_config = {
\   "_" : {
\       "outputter" : "message",
\   },
\}
let g:quickrun_no_default_key_mappings = 1
'''
hook_source = '''
nmap <Leader>rr <Plug>(quickrun)
'''

[[plugins]]
repo = 'vim-test/vim-test'
on_ft = ['go', 'java', 'javascript', 'typescript', 'lua', 'scala' ]
if = '!exists("g:vscode")'
hook_add = '''
let test#strategy = "neovim"
'''
hook_source = '''
nmap <silent> <leader>tn :TestNearest<CR>
nmap <silent> <leader>tf :TestFile<CR>
nmap <silent> <leader>ts :TestSuite<CR>
nmap <silent> <leader>tl :TestLast<CR>
nmap <silent> <leader>tg :TestVisit<CR>
'''

[[plugins]]
repo = 'tpope/vim-commentary'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'sbdchd/neoformat'
on_cmd = ['Neoformat', 'Neoformat!']
if = '!exists("g:vscode")'

[[plugins]]
repo = 'honza/vim-snippets'
depends = 'coc.nvim'
if = 'has("python3")'
if = '!exists("g:vscode")'
merged = 0


[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
if = '!exists("g:vscode")'
