[[plugins]]
merged = 1
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
merged = 1
on_map = { ox = '<Plug>' }
hook_add = '''
let g:textobj_indent_no_default_key_mappings=1

xmap ll <Plug>(textobj-indent-i)
omap ll <Plug>(textobj-indent-i)
xmap lL <Plug>(textobj-indent-same-i)
omap lL <Plug>(textobj-indent-same-i)

xmap al <Plug>(textobj-indent-a)
omap al <Plug>(textobj-indent-a)
xmap aL <Plug>(textobj-indent-same-a)
omap aL <Plug>(textobj-indent-same-a)
'''

[[plugins]]
repo = 'sgur/vim-textobj-parameter'
depends = 'vim-textobj-user'
merged = 1
on_map = { ox = '<Plug>' }
hook_add = '''
let g:textobj_parameter_no_default_key_mappings=1

xmap la <Plug>(textobj-parameter-i)
omap la <Plug>(textobj-parameter-i)
xmap aa <Plug>(textobj-parameter-a)
omap aa <Plug>(textobj-parameter-a)
'''
